"""mm-contracts: shared Pydantic models for Mathodology."""

from mm_contracts.agent_io import (
    AgentEvent,
    AnalyzerOutput,
    ApproachSketch,
    Attachment,
    CellExecution,
    CoderOutput,
    ConsultedMethod,
    DataRequirement,
    Equation,
    Figure,
    MethodNode,
    ModelSpec,
    Paper,
    PaperDraft,
    PaperSection,
    ProblemInput,
    ReasoningEffort,
    RunResult,
    SearchConfig,
    SearchEngine,
    SearchFindings,
    SearchPrimary,
    TokenUsage,
    Variable,
)

__all__ = [
    "AgentEvent",
    "AnalyzerOutput",
    "ApproachSketch",
    "Attachment",
    "CellExecution",
    "CoderOutput",
    "ConsultedMethod",
    "DataRequirement",
    "Equation",
    "Figure",
    "MethodNode",
    "ModelSpec",
    "Paper",
    "PaperDraft",
    "PaperSection",
    "ProblemInput",
    "ReasoningEffort",
    "RunResult",
    "SearchConfig",
    "SearchEngine",
    "SearchFindings",
    "SearchPrimary",
    "TokenUsage",
    "Variable",
]
