"""mm-contracts: shared Pydantic models for Mathodology."""

from mm_contracts.agent_io import (
    AgentEvent,
    AnalyzerOutput,
    ApproachSketch,
    Attachment,
    CellExecution,
    CoderOutput,
    ConsultedMethod,
    DataRequirement,
    Equation,
    MethodNode,
    ModelSpec,
    PaperDraft,
    PaperSection,
    ProblemInput,
    RunResult,
    TokenUsage,
    Variable,
)

__all__ = [
    "AgentEvent",
    "AnalyzerOutput",
    "ApproachSketch",
    "Attachment",
    "CellExecution",
    "CoderOutput",
    "ConsultedMethod",
    "DataRequirement",
    "Equation",
    "MethodNode",
    "ModelSpec",
    "PaperDraft",
    "PaperSection",
    "ProblemInput",
    "RunResult",
    "TokenUsage",
    "Variable",
]
