/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProblemInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run state + event history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/figures/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a figure file written by the worker
         * @description Returns the PNG / JPEG / SVG written at
         *     `<RUNS_DIR>/<run_id>/figures/<path>`. Path traversal is rejected
         *     (403). Only image extensions are served (415 for anything else).
         *     Response has `Cache-Control: private, max-age=3600`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                    /** @description Relative path under the run's `figures/` directory. */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                        "image/jpeg": string;
                        "image/svg+xml": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (path traversal) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Payload too large (>16 MiB) */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/notebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the executed Jupyter notebook for a run
         * @description Returns `<RUNS_DIR>/<run_id>/notebook.ipynb` as an attachment with
         *     `Content-Type: application/x-ipynb+json`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ipynb+json": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completions (passthrough to configured providers)
         * @description Body mirrors OpenAI's chat/completions schema. When `stream=true` returns SSE.
         *     Set `X-Run-Id` and `X-Agent` headers so the gateway tags cost accounting and
         *     fans tokens into the matching WS run stream.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Run-Id"?: string;
                    "X-Agent"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
            redis_ok?: boolean;
            postgres_ok?: boolean;
        };
        ProblemInput: {
            problem_text: string;
            /**
             * @default other
             * @enum {string}
             */
            competition_type: "mcm" | "icm" | "cumcm" | "huashu" | "other";
            attachments?: components["schemas"]["Attachment"][];
            /** @description Force a specific model; otherwise router picks per-agent defaults. */
            model_override?: string;
            /**
             * @description Cross-provider reasoning-effort hint. Translated in the gateway to
             *     each provider's native API: OpenAI-compat emits `reasoning_effort`
             *     + `reasoning.effort`; Anthropic emits
             *     `thinking.budget_tokens` (low=1024, medium=4096, high=16384).
             *     `off` suppresses emission entirely.
             * @default medium
             * @enum {string}
             */
            reasoning_effort: "off" | "low" | "medium" | "high";
        };
        Attachment: {
            name: string;
            /** @enum {string} */
            kind: "csv" | "xlsx" | "pdf" | "image" | "text";
            content_base64?: string;
        };
        RunCreated: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued";
        };
        Run: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            problem_text?: string;
            cost_rmb?: number;
            notebook_path?: string;
            paper_path?: string;
            events?: components["schemas"]["AgentEvent"][];
        };
        AgentEvent: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string|null} */
            agent?: "analyzer" | "modeler" | "coder" | "writer" | "critic" | "searcher" | null;
            /** @enum {string} */
            kind: "stage.start" | "stage.done" | "log" | "token" | "cost" | "agent.output" | "kernel.stdout" | "kernel.figure" | "error" | "done";
            seq: number;
            /** Format: date-time */
            ts: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            /** @default 0.2 */
            temperature: number;
            max_tokens?: number;
            /** @default false */
            stream: boolean;
            response_format?: {
                [key: string]: unknown;
            };
            /**
             * @description Optional reasoning-effort hint. Gateway translates it per provider:
             *     OpenAI-compat bodies get `reasoning_effort` and
             *     `reasoning.effort` set; Anthropic bodies get
             *     `thinking.budget_tokens` (low=1024, medium=4096, high=16384) plus a
             *     conditional `max_tokens` bump. `off` or unset omits emission.
             * @enum {string}
             */
            reasoning_effort?: "off" | "low" | "medium" | "high";
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            name?: string;
        };
        ChatCompletionResponse: {
            id: string;
            model: string;
            created?: number;
            choices: {
                index?: number;
                message?: components["schemas"]["ChatMessage"];
                finish_reason?: string;
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
