// Generated by openapi-typescript; run `just gen-ts` to regenerate from
// packages/contracts/openapi.yaml. This stub is checked in so the workspace
// typechecks before the first generation.
export {};
